#!/usr/bin/env python3
"""Embeds the pages of src/web/ into src/se_web_pages.h, served by the HTTP control server.

Run it after changing a page:  python3 tools/embed_web_pages.py
Byte arrays are used because compilers limit the length of string literals.
"""
import os

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PAGES = [("remote.html", "se_web_remote_html"), ("overlay.html", "se_web_overlay_html")]

out = ["// Generated by tools/embed_web_pages.py from src/web/, do not edit.",
       "#ifndef SE_WEB_PAGES_H", "#define SE_WEB_PAGES_H", ""]
for file_name, symbol in PAGES:
    data = open(os.path.join(ROOT, "src", "web", file_name), "rb").read()
    out.append(f"// src/web/{file_name}")
    out.append(f"static const unsigned char {symbol}[] = {{")
    for i in range(0, len(data), 24):
        out.append("  " + ",".join(str(b) for b in data[i:i+24]) + ",")
    out.append("  0};")
    out.append(f"static const unsigned long {symbol}_size = {len(data)};")
    out.append("")
out.append("#endif")
open(os.path.join(ROOT, "src", "se_web_pages.h"), "w").write("\n".join(out) + "\n")
print("Wrote src/se_web_pages.h")
