name: Build macOS (Libretro)
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on: macos-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
      - name: Configure & Build 🔧
        run: |
          cmake -B build -DRETRO_CORE_ONLY=ON
          cmake --build build --target skyemu_libretro --parallel "$(sysctl -n hw.ncpu)"
          cd build && zip skyemu_libretro.zip skyemu_libretro.dylib ../skyemu_libretro.info
      - name: Upload 🚀
        uses: actions/upload-artifact@v7
        with:
          name: MacOSRelease (Libretro)
          path: build/skyemu_libretro.zip
