name: Build Windows
on: [push, pull_request]
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  build-and-deploy:
    runs-on: windows-2022
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
      - name: Get latest CMake and ninja
        uses: lukka/get-cmake@latest
      - name: Build 🔧
        # SkyEmu.exe and SkyEmu.dll
        run: |
          cmake -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_SYSTEM_VERSION=10.0.19041.0
          cmake --build build --config RelWithDebInfo --parallel
      - name: Upload 🚀
        uses: actions/upload-artifact@v7
        with:
          name: WindowsRelease
          path: build/bin/RelWithDebInfo
